### ISSUE TITLE
네이버 지도 다른 의존성 사용

### ISSUE THREAD

**Issue by found-cake** [Antraxmin/SoonPlus-App#1]
현재 사용중이신 네이버 지도 플러그인의 최신 커밋이 무려 2년전 이고 사용중이신 flutter 버전하고 안 맞습니다.
따라서 다른 의존성을 사용하시는 것이 좋을 것 같습니다.

추천하는 네이버 지도 의존성
https://github.com/note11g/flutter_naver_map

**Comment by Antraxmin** [comment]
알고 있습니다.
